### PR TITLE
input: fix pasting

### LINKED ISSUE #18: input: pasting doesn't work
Because we are reading 4 bytes at a time, and assuming that the non-escape code part will only use the first byte, pasting doesn't work. We probably want to read byte by byte instead.

### PR DESCRIPTION
**Pull request by nloomans**
Previously the input__read_keypress function read 4 bytes at once,
assuming that a regular character would only be in the first byte
because a user couldn't type so fast. This assumption was flawed as
pasting text would cause all 4 bytes to be filled with data. The result
would be that, if pasting text, some but not all characters would
actually be recorded.

This patch switches to a new system which reads the input byte by byte
instead. This will also allow parsing of more complex control codes in
the future.

Fixes #18

### CODE REVIEW

File: src/input/read_keypress.c [hunk 1]
```diff
@@ -15,33 +15,56 @@
...
+		keypress->type = INPUT__READ_RETURN;
+	else if (ft_isprint(c))
 	{
-		keypress->type = INPUT__READ_TYPE_REG;
-		keypress->c = buffer[0];
+		keypress->type = INPUT__READ_TEXT;
+		keypress->c = c;
 	}
-	return (error_none());
+	return (error);
```
Comment (aholster) [inline src/input/read_keypress.c:69]: error handling

**Comment by nloomans** [comment]
v2: simplified needlessly complicated error handling.
